# Colores por defecto
[colors.primary]
background = '#121212'
foreground = '#e4718e'

# Color del cursor
[colors.cursor]
text = '#F81CE5'
cursor = '#ffffff'

# Colores primarios
[colors.normal]
black   = '#000000'
red     = '#fe0100'
green   = '#33ff00'
yellow  = '#feff00'
blue    = '#0066ff'
magenta = '#cc00ff'
cyan    = '#00ffff'
white   = '#d0d0d0'

# Colores brillantes
[colors.bright]
black   = '#808080'
red     = '#fe0100'
green   = '#33ff00'
yellow  = '#feff00'
blue    = '#0066ff'
magenta = '#cc00ff'
cyan    = '#00ffff'
white   = '#FFFFFF'

# Configuracion de las fuentes
[font]
size = 15.0

[font.normal] 
family = 'JetBrains Mono Nerd Font'
style = 'regular'

# Config de la Ventana (i.e. transparencia)
[window]
opacity = 0.9
decorations = 'transparent'
